name: Publish to NPM

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        description: Release type
        required: true
        options:
          - release
          - canary
      version:
        type: string
        description: Version
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      GH_TOKEN: ${{secrets.GH_TOKEN}}
      NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.GH_TOKEN}}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - name: Setup NPM authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
          echo "@twick:registry=https://registry.npmjs.org/" >> ~/.npmrc

      - name: Configure git
        run: |
          git config --global user.email "167322027+twick-bot@users.noreply.github.com"
          git config --global user.name "twick-bot"

      - name: Install dependencies
        run: npm ci

      - name: Build all packages
        run: npx lerna run build

      - name: Publish release
        if: ${{ inputs.releaseType == 'release' }}
        run: npx lerna publish --yes --force-publish --exact ${{ inputs.version }} --access public

      - name: Publish canary
        if: ${{ inputs.releaseType == 'canary' }}
        run: npx lerna publish --yes --canary --force-publish --access public
